### ISSUE TITLE
"The bingus.link code "example" has been visited [blank] time(s)"

### ISSUE THREAD

**Issue by lerichardson** [trevorthalacker/bingus.link#7]
I'm not sure why this is happening. I created this link a couple of hours ago and when I go to the `/hits/[link]` page, it's not showing any analytics.
![image](https://user-images.githubusercontent.com/72626657/116015849-a2add480-a5ef-11eb-8fd4-00f05ee4615c.png)
Then, the console reports that this page actually doesn't exist:
![image](https://user-images.githubusercontent.com/72626657/116016017-31225600-a5f0-11eb-87c6-8439980f9856.png)
But the link, `rkTpQCUlq` works just fine.

**Comment by trevorthalacker** [comment]
Attempting to visit https://bingus.link/hits/rkTpQCUlq right now shows that the code has been visited 1 time. Did you visit the shortened URL at all before visiting the hit count page?

**Comment by lerichardson** [comment]
Yep. A couple times, making me think it's my browser.

**Comment by lerichardson** [comment]
Ah, it's my browser's cache. My bad,

**Comment by trevorthalacker** [comment]
Huh...
The page showing as a 404 was a mistake on my end that I have fixed locally, but hit counting happens on the server-side, so your browser should not be affecting it.
