### ISSUE TITLE
Embed Previews using JS

### ISSUE THREAD

**Issue by lerichardson** [trevorthalacker/bingus.link#9]
Continuing from https://mobile.twitter.com/trevorthalacker/status/1387220988966817792

**Comment by trevorthalacker** [comment]
Options:

1. Create JavaScript (or maybe TS, webpack is already setup here) to handle embed previews
2. Use another language (WASM, elm, etc.) ?that supports compiling to JS.
3. No embed previews

**Comment by trevorthalacker** [comment]
This has been added in #10
